from langchain_core.documents import Document

join_details = """
                Schema : fl_lms
                accrual_balances.loannumber = loan_onboarding.loannumber
                accrual_balances.loannumber = loan_filters.loannumber
                loan_filters.loannumber = loan_onboarding.loannumber

                Schema : public
                los_borrower_application.id = loan_offer.id
                los_offer.id = loan_address.id
                los_borrower_application.id = loan_address.id"""

schema_info = """Schema : fl_lms
                contains tables : accrual_balances, loan_onboarding, loan_filters

                Schema : public
                contains tables : los_borrower_application, los_offer, los_address
                
                schema : cdp
                contains tables : customerdataproductfinal"""

documents = [
    # --- accrual_balances ---

    Document(
        page_content="Table: accrual_balances. This table tracks the financial state of loans, including outstanding balances, due payments, and charge-off status.",
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to accrual_balances (Identifiers):

            - accrual_balances_hevo_id: Identification string generated by hevo (character varying)
            - loannumber: Loan number or loan identification , it is generally an alphanumeric value (character varying)
            - scheduleversion: Version of the loan (character varying)
            - processingdate: Latest Processing date from accrual balance (timestamp without time zone)
            - tenantid: Unique ID for the tenent identification (character varying)
            - createddate: Date on which loan got created (timestamp without time zone)
        """.strip(),
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "identifiers"
        }
    ),

    Document(
        page_content="""
            Fields related to accrual_balances (Delinquency Tracking):

            - due_dpddays: Number of days since dpd is due (bigint)
            - due_missedinstallmentno: All the missed installment numbers (bigint)
            - due_paymentmisseddate: All missed payment dates (timestamp without time zone)
            - due_dpdstartdate: Start date of when dpd_due started (timestamp without time zone)
            - due_missedscheduledate: All missed schedule dates (timestamp without time zone)
        """.strip(),
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "delinquency_tracking"
        }
    ),

    Document(
        page_content="""
            Fields related to accrual_balances (Outstanding Balances):

            - pbot_additionaloutstandinginterest: Total additional interest outstanding till date (double precision)
            - pbot_totalfeeoutstanding: Total fee outstanding till date (double precision)
            - pbot_totalinterestoutstanding: Total interest outstanding till date (double precision)
            - pbot_totalprincipaloutstanding: Total principal outstanding till date (double precision)
            - pbot_totaloutstanding: Total outstanding till date (double precision)
            - pbot_minimumamountdue: Minimum amount due till date (double precision)
            - pbot_totalscheduleinterestdue: Total schedule interest due till date (double precision)
            - pbot_asofdatepbot: A date around which all the pbot information is provided (timestamp without time zone)
            - pboc_currentinterestoutstanding: Total due current interest outstanding (double precision)
            - pboc_totalcurrentoutstanding: Total due current outstanding (double precision)
            - pboc_cummulativeinterestaccured: Total du cummulative interest accrued (double precision)
            - pboc_asofdatepboc: Particular Date related to all the object data data (timestamp without time zone)
            - pboc_expectedcumulativeprincipal: Total due expected cumlative principal (double precision)
            - pboc_currentprincipaloutstanding: Total due current principal outstanding (double precision)
        """.strip(),
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "outstanding_balances"
        }
    ),

    Document(
        page_content="""
            Fields related to accrual_balances (Payment & Payoff):

            - installmentamount: Amount to be paid in each installment or EMI (double precision)
            - dailyrate: Interest rate on daily basis (double precision)
            - paymentinfo_lastpaymentreceiveddate: Date on which last payment is received (timestamp without time zone)
            - paymentinfo_paidfeeamount: Amount paid as fees (double precision)
            - paymentinfo_lastpaymentamount: Amount paid in the last payment (double precision)
            - paymentinfo_cumulativetotalpaid: Total how much of amount paid for the loan (double precision)
            - payoff_payoffdate: Last payment date on which loan got paid off (timestamp without time zone)
            - payoff_payoffamount: Amount paid in last transaction to make loan Payoff (double precision)
        """.strip(),
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "payment_and_payoff"
        }
    ),

    Document(
        page_content="""
            Fields related to accrual_balances (Charge-Off):

            - chargeoff_chargeoffdate: Date onwhich loan got charge off (timestamp without time zone)
            - chargeoff_chargeoffamount: Total outstanding amount when loan got charged off (double precision)
            - chargeoff_interestoutstanding: The interest amount still outstanding after charge-off. (double precision)
            - chargeoff_feeoutstanding: The fees still outstanding after charge-off. (double precision)
            - chargeoff_reasonofchargeoff: The reason for charging off the loan. (character varying)
            - chargeoff_currentprincipaloutstanding: The principal still owed after the charge-off. (double precision)
            - chargeoff_currentinterestoutstanding: The interest still owed after the charge-off. (double precision)
            - chargeoff_totalcurrentoutstanding: The total amount (principal + interest) still owed after charge-off. (double precision)
            - chargeoff_recoveredamount: The amount recovered after the loan charge-off. (double precision)
            - chargeoff_pendingrecoveryamount: The amount still pending recovery after charge-off. (double precision)
            - chargeoff_paidchargeoffdate: The date when the charge-off amount was paid. (timestamp without time zone)
            - chargeoff_recoveredprincipalamount: The amount of the principal recovered after charge-off. (double precision)
            - chargeoff_recoveredinterestamount: The amount of the interest recovered after charge-off. (double precision)
            - chargeoff_recoveredfeeamount: The amount of the fees recovered after charge-off. (double precision)
        """.strip(),
        metadata={
            "table_name": "accrual_balances",
            "chunk_type": "charge_off"
        }
    ),

    # --- loan_filters ---

    Document(
        page_content="Table: loan_filters. This table contains loan master data, borrower demographics, loan terms, status information, and key dates for loan lifecycle management.",
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Loan Identification):

            - loan_filters_hevo_id: Identification string generated by hevo (character varying)
            - tenantid: Unique ID for the tenent identification (character varying)
            - loannumber: Loan number or loan identification , it is generally an alphanumeric value (character varying)
            - loanapplicationnumber: Application Number of Loan (character varying)
            - additionalrefid: unique reference id for the loan (character varying)
            - funderid: Funder id of loan if there are multiple funders for same tenant (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "loan_identification"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Loan Dates):

            - loanonboardeddate: date of onboarding of the loan (timestamp without time zone) onboarding_date
            - loanfundeddate: funded date of the Loan (timestamp without time zone)
            - loanstartdate: Loan Start date (timestamp without time zone)
            - processingdate: Latest Processing date from accrual balance (timestamp without time zone)
            - firstpaymentdate: First date of payment (timestamp without time zone)
            - statusdate: Date on which status got updated (timestamp without time zone)
            - consideredfundeddate: Date on which loan funded (timestamp without time zone)
            - loanenddate: End date of the Loan (timestamp without time zone)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "loan_dates"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Loan Terms & Amounts):

            - loanproductid: Product ID of Loan (character varying)
            - productportfoliotype: Protfolio type of loan (character varying)
            - productcategory: Category in which product is fallen (character varying)
            - tenure: Complete Tenure of the loan (bigint)
            - annualrate: The annual interest rate applied to the loan. (double precision)
            - loanamount: The original loan amount approved. (double precision)
            - fundedamount: Total funded amount (double precision)
            - principalamount: Total Principal amount of loan (double precision)
            - businessmaxlimitamount: Maximum limit amount for buisness (double precision)
            - consideredfundedamount: Amount got funded (double precision)
            - consideredtenure: No of total payements need to be made by borrower (bigint)
            - paymentfrequency: how frquetly payment should be done either Monthly, SemiMonthly or weekly (character varying)
            - frequencyrate: The numeric frequency value (e.g., 12 for monthly). (double precision)
            - dailyrate: Interest rate on daily basis (double precision)
            - factorrate: Alternative rate used for interest calculations, if applicable. (double precision)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "loan_terms_and_amounts"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Loan Status & Modification):

            - statusname: Current stage of loan (character varying)
            - currentloanscheduleversion: latest schedule version of the loan (character varying)
            - statuscode: Status Name internally have some code on which current stage loan can be predicted (character varying)
            - isautopay: Stating either loan is autopay or not (boolean)
            - workflowstatus: Current status of the loan as per final change in the loan (bigint)
            - installmentdateifholiday: If the installment date is holiday (character varying)
            - autofunded: boolean field to check whether loan is auto funded or not (boolean)
            - loanmodreason: Reason why loan got modified (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "loan_status_and_modification"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Borrower Information):

            - primaryapplicantcity: city of primary applicant (character varying)
            - primaryapplicantstate: city name of the primary applicant (character varying)
            - primaryapplicantzip: zip code of the primary applicant address (character varying)
            - primaryapplicantdob: Date of birth of the primary applicant. (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "borrower_information"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_filters (Payment Summary):

            - pboc_cummulativeinterestaccured: Total du cummulative interest accrued (double precision)
            - paymentinfo_paidinterestamount: Total interest paid so far by the borrower. (double precision)
            - pbot_totalinterestoutstanding: Total interest outstanding till date (double precision)
            - pbot_totaloutstanding: Total outstanding till date (double precision)
            - due_missedinstallmentno: All the missed installment numbers (bigint)
            - paymentinfo_lastpaymentamount: Amount paid in the last payment (double precision)
            - numberofpaymentmade: The number of payments successfully made to date. (bigint)
        """.strip(),
        metadata={
            "table_name": "loan_filters",
            "chunk_type": "payment_summary"
        }
    ),

    # --- loan_onboarding ---

    Document(
        page_content="Table: loan_onboarding. This table contains detailed information about the loan application and onboarding process, including applicant details, credit scores, and custom fields.",
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_onboarding (Loan Identification):

            - loan_onboarding_hevo_id: Identification string generated by hevo (character varying)
            - loannumber: Loan number or loan identification , it is generally an alphanumeric value (character varying)
            - tenantid: Unique ID for the tenent identification (character varying)
            - loanapplicationnumber: Application Number of Loan (character varying)
            - additionalrefid : unique reference id for the loan (character varying)
            - _id: Unique identification id for each record (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "loan_identification"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_onboarding (Product & Dates):

            - loanonboardeddate: date of onboarding of the loan (timestamp without time zone)
            - loanfundeddate: funded date of the Loan (timestamp without time zone)
            - loanenddate: End date of the Loan (timestamp without time zone)
            - loanproductid: Product ID of Loan (character varying)
            - productcategory: Category in which product is fallen (character varying)
            - productportfoliotype: Protfolio type of loan (character varying)
            - loantype: Type of loan offered (e.g., term loan, line of credit). (bigint)
            - firstpaymentdate: First date of payment (timestamp without time zone)
            - loanstartdate: Loan Start date (timestamp without time zone)
        """.strip(),
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "product_and_dates"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_onboarding (Credit & Risk Scores):

            - customfields_credolab_score: A score provided by CredoLab for credit risk assessment. (character varying)
            - customfields_psychometric_score: Psychometric score for evaluating borrower behavior. (character varying)
            - customfields_income: Declared or estimated income of the applicant. (character varying)
            - customfields_pti: Payment-to-Income ratio of the borrower. (character varying)
            - customfields_teti: Total Expense-to-Income ratio of the borrower. (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "credit_and_risk_scores"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_onboarding (Borrower Details):

            - borrowerid : Primary key and the borrowerid. (character varying)
            - customfields_time_in_job: Duration the borrower has held their current job. (character varying)
            - customfields_employer_name: Name of the borrower’s employer. (character varying)
            - customfields_new_to_borrowing: Flag indicating if the borrower is new to credit. (character varying)
            - customfields_education: Education level of the primary applicant. (character varying)
            - primaryapplicantdetails_name_middle: Middle name of the primary applicant. (character varying)
            - city: City of the borrower’s residence. (character varying)
            - state: State of the borrower’s residence. (character varying)
            - addresstype: Type of address provided (e.g., residential, business). (character varying)
        """.strip(),
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "borrower_details"
        }
    ),

    Document(
        page_content="""
            Fields related to loan_onboarding (Autopay & Custom Fields):

            - customfields_advance_pay_loan: Indicator for advance salary or payday loan. (character varying)
            - customfields_auto_debit_authorization: Flag indicating if auto-debit is authorized. (character varying)
            - customfields_program_type: Indicates special programs or schemes the loan belongs to. (character varying)
            - reasonforautopaypause: Reason auto-pay has been paused. (character varying)
            - autopaystopdate: Date when auto-pay was stopped. (timestamp without time zone)
        """.strip(),
        metadata={
            "table_name": "loan_onboarding",
            "chunk_type": "autopay_and_custom_fields"
        }
    ),

    # --- los_borrower_application ---

    Document(
        page_content="Table: los_borrower_application. This table stores comprehensive information about loan applications, including borrower details, application status, financial metrics, and tracking information.",
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to los_borrower_application (Identifiers & Core Details):

            - id: Unique identifier for the application or record (character varying)
            - borrowerid: Unique identifier assigned to the borrower (character varying)
            - cid: Customer Identification Number; a unique number assigned to a customer (character varying)
            - identifier: Additional unique identifier associated with the applicant or application (character varying)
            - prospectid: Unique identifier assigned to a prospective applicant or lead (character varying)
            - tenant: In multi-tenant systems, this refers to the specific client or organization that owns or has access to a particular set of data or services (character varying)
            - email: Email address of the applicant (character varying)
            - phone: Contact phone number of the applicant (character varying)
            - homeaddress: Residential address of the applicant (character varying)
            - companybusinessname: The registered name of the applicant's business (character varying)
            - legalstructure: The legal framework or structure of the business (e.g., LLC, Corporation) (character varying)
            - inbusinesssince: The year or date since the business has been operational (timestamp without time zone)
            - timeinbusiness: Duration for which the business has been operational (double precision)
            - industry: The sector or industry in which the applicant's business operates (character varying)
            - industrytier: Classification or tier of the industry based on predefined criteria (character varying)
        """.strip(),
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "identifiers_core_details"
        }
    ),

    Document(
        page_content="""
            Fields related to los_borrower_application (Application Status & Tracking):

            - stage: Current stage or phase of the application process (character varying)
            - submissionstage: The stage at which the application was submitted (character varying)
            - applicationtagtext: Textual tags or labels assigned to the application for categorization or tracking purposes (character varying)
            - applicationverification: Status indicating whether the application details have been verified (double precision)
            - applicationrejectedreasons: Reasons provided for the rejection of the application (character varying)
            - createdon: Date and time when the application or record was created (timestamp without time zone)
            - submittedon: Date and time when the application was submitted (timestamp without time zone)
            - updateon: Date and time when the record was last updated (timestamp without time zone)
            - laststageupdateon: Date and time when the application last moved to a different stage (timestamp without time zone)
            - fundedon: Date when the loan or funding was disbursed (timestamp without time zone)
            - expiryon: Date when a particular document, offer, or status expires (timestamp without time zone)
            - onboardedcompleted: Flag indicating whether the onboarding process has been completed (double precision)
            - dealtype: The type or category of the deal or loan applied for (character varying)
            - loantype: The category or type of loan applied for (e.g., term loan, line of credit) (character varying)
            - offertype: Specifies the type or category of loan offer presented to the applicant (character varying)
            - channel: The medium or source through which the application was submitted (e.g., online, branch) (character varying)
            - leadsource: The origin or source from which the lead or application was generated (character varying)
            - applyipaddress: The IP address from which the application was submitted (character varying)
            - utmcampaign: UTM parameter indicating the campaign source for tracking purposes (character varying)
            - utmcontent: UTM parameter indicating specific content for tracking purposes (character varying)
            - utmmedium: UTM parameter indicating the medium through which the application was acquired (character varying)
            - utmsource: UTM parameter indicating the source of the traffic or lead (character varying)
            - version: Version number of the application or document (double precision)
            - metainformation: Additional metadata or information related to the application (character varying)
            - submethod: Sub-category or specific method used within a broader category (character varying)
            - brokerids: Broker Identification Numbers (character varying)
            - brokernames: Names of the brokers involved (character varying)
            - branch: The branch associated with the application (character varying)
            - salesperson: The salesperson associated with the application (character varying)
        """.strip(),
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "application_status_tracking"
        }
    ),

    Document(
        page_content="""
            Fields related to los_borrower_application (Financials & Loan Details):

            - annualrevenue: The total revenue generated by the business annually (double precision)
            - systemassessedannualsales: Annual sales figure as assessed by the system (double precision)
            - lowestmonthlycreditcardreceipt: The lowest amount received from credit card transactions in a month (double precision)
            - loanamount: The amount of loan requested or approved (double precision)
            - loancount: The number of loans the applicant has taken previously (double precision)
            - ficoscore: Credit score of the applicant as determined by the Fair Isaac Corporation (FICO) (character varying)
            - availableproducts: List of products or services available to the applicant (character varying)
            - ecomstatus: Status related to e-commerce activities of the applicant (character varying)
            - econstatus: Economic status or classification of the applicant (character varying)
            - selfdisclosedvalue: Value or information disclosed by the applicant themselves (double precision)
        """.strip(),
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "financials_loan_details"
        }
    ),

    Document(
        page_content="""
            Fields related to los_borrower_application (Duplication & Verification Flags):

            - dedupemail: Flag indicating whether the email address has been checked for duplicates (double precision)
            - dedupeverfunded: Flag indicating whether the applicant has ever received funding before (double precision)
            - dedupfederaltaxid: Flag indicating whether the federal tax ID has been checked for duplicates (double precision)
            - dedupfunded: Flag indicating whether the applicant has been funded before (double precision)
            - deduplegalbusinessname: Flag indicating whether the legal business name has been checked for duplicates (double precision)
            - dedupownerssn: Flag indicating whether the owner's Social Security Number (SSN) has been checked for duplicates (double precision)
            - dedupzipcode: Flag indicating whether the ZIP code has been checked for duplicates (double precision)
            - hasdiffhomeaddress: Flag indicating whether the home address provided differs from previous records (double precision)
            - hasdifflegalname: Flag indicating whether the legal name provided differs from previous records (double precision)
            - isallownersubmited: Flag indicating whether all owners have submitted their information (double precision)
            - isemailagefound: Flag indicating whether the age of the email address could be determined (double precision)
            - emailagestatus: Status indicating the age or longevity of the provided email address (character varying)
        """.strip(),
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "duplication_verification_flags"
        }
    ),

    Document(
        page_content="""
            Fields related to los_borrower_application (Risk & System Integrations):

            - deceased: Indicates whether the individual is deceased (true for deceased, false for living) (double precision)
            - cumulativeownership: Total percentage of ownership held collectively by the owners (double precision)
            - nolowdesignation: Specific designation or classification related to the applicant, possibly indicating 'No Low' risk (character varying)
            - riskchannel: The channel through which the risk assessment was conducted (character varying)
            - loanfromlmsstatus: Status of the loan as per the Loan Management System (LMS) (character varying)
            - lmsdataupdatedon: Date and time when the Loan Management System data was last updated (timestamp without time zone)
            - lmsloannumber: Unique loan number assigned by the Loan Management System (character varying)
            - plaidworkflowstatus: Status of the workflow associated with Plaid, a financial services company (character varying)
        """.strip(),
        metadata={
            "table_name": "los_borrower_application",
            "chunk_type": "risk_system_integrations"
        }
    ),

    # --- los_offer ---
    Document(
        page_content="Table: los_offer. This table details various loan offers made to borrowers, including financial terms, status, and related fees.",
        metadata={
            "table_name": "los_offer",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to los_offer (Identifiers & Offer Management):

            - id: Unique identifier for this record (primary key) (character varying)
            - borrower_application_id: Reference ID linking to the borrower’s application (character varying)
            - tenant: Owning organization (multi-tenant context) (character varying)
            - product: The loan product type (e.g., line of credit, term loan) (character varying)
            - offersversion: Version number of the offer — for tracking changes (numeric)
            - version: Version number for tracking changes or managing concurrency (numeric)
            - createdon: Timestamp when the record was created (timestamp without time zone)
            - updateon: Timestamp when this record was last updated (timestamp without time zone)
            - presentedon: When the offer was presented to the borrower (timestamp without time zone)
            - isgenerated: Flag showing if the offer was system-generated (boolean)
        """.strip(),
        metadata={
            "table_name": "los_offer",
            "chunk_type": "identifiers_offer_management"
        }
    ),

    Document(
        page_content="""
            Fields related to los_offer (Offer Status & Outcomes):

            - active: Flag indicating if the offer or record is currently active (boolean)
            - isactiveoffer: Boolean indicating if the offer is currently valid/active (boolean)
            - disable: Flag indicating if the offer is disabled (possibly deprecated or rejected) (boolean)
            - selected: Boolean or flag indicating if this offer was selected (boolean)
            - rejectedreason: Reason for offer rejection, if any (character varying)
            - result: Status or outcome of the offer process (character varying)
            - deceased: Possibly refers to the borrower—flag for deceased status (boolean)
            - pom: Possibly short for "Plan of Management" or "Point of Money" – domain-specific (boolean)
        """.strip(),
        metadata={
            "table_name": "los_offer",
            "chunk_type": "offer_status_outcomes"
        }
    ),

    Document(
        page_content="""
            Fields related to los_offer (Financial Terms & Amounts):

            - amountrequested: The amount the borrower has requested (numeric)
            - approvedamount: The amount that has been approved (numeric)
            - finalamount: Final loan amount after calculations like fees, holdbacks, etc. (numeric)
            - fundedamount: Actual amount disbursed to borrower (numeric)
            - proceedtocustomer: Amount actually received by the customer after all deductions (numeric)
            - totalprincipal: Original principal amount (numeric)
            - apr: Annual Percentage Rate of the loan (numeric)
            - interestrate: The raw interest rate (may differ from APR) (numeric)
            - listrate: Listed or advertised rate (could be for display purposes) (numeric)
            - minrate: Minimum rate in the offered range (numeric)
            - targetrate: Desired interest rate for the borrower (numeric)
            - totalinterest: Total interest expected over the life of the loan (numeric)
            - totalpayback: Total amount to be repaid (principal + interest + fees) (numeric)
            - paymentamount: Regular scheduled payment amount (numeric)
            - payoffamount: Total remaining amount to fully pay off the loan (numeric)
            - term: Loan term (likely in months or days) (numeric)
            - freqofpayment: Frequency of payments (e.g., weekly, monthly) (numeric)
            - frequency: Another field for payment frequency—might duplicate or supplement freqofpayment (character varying)
            - maxline: Maximum credit line available (numeric)
            - utilization: How much of the credit line or offer is being used (numeric)
            - paidoffpercentage: % of the loan that has been paid off (numeric)
        """.strip(),
        metadata={
            "table_name": "los_offer",
            "chunk_type": "financial_terms_amounts"
        }
    ),

    Document(
        page_content="""
            Fields related to los_offer (Fees & Adjustments):

            - adjustmentpercentage: A percentage value used to adjust amounts, possibly during underwriting (numeric)
            - holdbackpercentage: Percentage held back (e.g., reserve or risk buffer) (numeric)
            - extensionfee: Fee charged for extending the loan term (numeric)
            - processingfee: Processing fee charged (numeric)
            - pomfee: Associated fee with the pom (numeric)
            - rolloveramount: Amount rolled over from a previous offer or loan (numeric)
            - otherbalance: Balance from other loans or obligations (numeric)
        """.strip(),
        metadata={
            "table_name": "los_offer",
            "chunk_type": "fees_adjustments"
        }
    ),

    Document(
        page_content="""
            Fields related to los_offer (Operational & Internal Details):

            - merchantrepresentative: Name or ID of the merchant's sales or service rep (character varying)
            - rateselector: Logic or identifier for rate selection (manual or system-defined) (character varying)
        """.strip(),
        metadata={
            "table_name": "los_offer",
            "chunk_type": "operational_internal_details"
        }
    ),

    Document(
        page_content="Table: los_address. This table stores address information, primarily for industry or applicant addresses.",
        metadata={
            "table_name": "los_address",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to los_address (Identifiers & Core Details):

            - id: Industry Address Id or Applicant Address Id (character varying)
            - city: City Name (character varying)
            - state: State Name (character varying)
        """.strip(),
        metadata={
            "table_name": "los_address",
            "chunk_type": "identifiers_core_details"
        }
    ),

    Document(
        page_content="""
            Fields related to los_address (Timestamps):

            - createdon: Creation Time & Date (character varying)
            - updateon: Time & Date of changes (character varying)
        """.strip(),
        metadata={
            "table_name": "los_address",
            "chunk_type": "timestamps"
        }
    ),

    Document(
        page_content="Table: customerdataproductfinal. This table aggregates final, processed data for customers and their associated products, including business demographics, loan application history, financial performance, and loan specific metrics.",
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "table_overview"
        }
    ),

    Document(
        page_content="""
            Fields related to customerdataproductfinal (Customer & Business Demographics):

            - borrowerid: Unique identifier assigned to the borrower (character varying)
            - companybusinessname: The registered name of the customer's business (character varying)
            - industry: The sector or industry in which the customer's business operates (character varying)
            - phone: Contact phone number of the customer (character varying)
            - email: Email address of the customer (character varying)
            - city: City Name of the business's location (character varying)
            - state: State Name of the business's location (character varying)
            - inbusinesssince: The year or date since the business has been operational (timestamp without time zone)
            - timeinbusiness: Duration for which the business has been operational (double precision)
        """.strip(),
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "customer_business_demographics"
        }
    ),

    Document(
        page_content="""
            Fields related to customerdataproductfinal (Financial Performance & Sales):

            - latestannualrevenue: The latest reported annual revenue generated by the business (numeric)
            - latestannualsales: The latest reported annual sales figure for the business (numeric)
            - medianfundedamount: The median amount of loans funded for the customer (numeric)
            - maxfundedamount: The maximum amount of a single loan funded for the customer (numeric)
            - medianrequestedamount: The median loan amount requested by the customer (numeric)
            - maxrequestedamount: The maximum loan amount requested by the customer (numeric)
            - total_loan_amount: The cumulative total amount of all loans associated with the customer (double precision)
            - ficoscore: Credit score of the applicant as determined by the Fair Isaac Corporation (FICO) (double precision)
        """.strip(),
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "financial_performance_sales"
        }
    ),

    Document(
        page_content="""
            Fields related to customerdataproductfinal (Application & Loan Activity Counts):

            - applicationcount: The total number of loan applications submitted by the customer (numeric)
            - loancount: The total number of loans the customer has taken (numeric)
            - active_loans: The count of currently active loans for the customer (bigint)
            - producttypecount: The count of unique product types the customer has applied for or received (numeric)
            - uniquechannelcount: The count of unique channels through which applications were submitted (numeric)
            - dealtypecount: The count of unique deal types associated with the customer's applications (numeric)
            - leadsourcecount: The count of unique lead sources for the customer's applications (numeric)
            - branchcount: The number of distinct branches associated with the customer's applications (numeric)
            - salespersoncount: The number of distinct salespersons associated with the customer's applications (numeric)
            - brokercount: The number of distinct brokers associated with the customer's applications (numeric)
        """.strip(),
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "application_loan_activity_counts"
        }
    ),

    Document(
        page_content="""
            Fields related to customerdataproductfinal (Loan Terms & Interest Rates):

            - minterm: The minimum loan term (in months or days) associated with the customer's loans (numeric)
            - maxterm: The maximum loan term (in months or days) associated with the customer's loans (numeric)
            - avgtenure: The average tenure (loan term) across the customer's loans (double precision)
            - minloanamount: The minimum loan amount the customer has received (double precision)
            - maxloanamount: The maximum loan amount the customer has received (double precision)
            - avgloanamount: The average loan amount the customer has received (double precision)
            - mininterestrate: The minimum interest rate applied to the customer's loans (double precision)
            - maxinterestrate: The maximum interest rate applied to the customer's loans (double precision)
            - averageinterestrate: The average interest rate applied to the customer's loans (double precision)
            - maxannualinterestrate: The maximum annual interest rate observed across the customer's loans (double precision)
            - avgannualinterestrate: The average annual interest rate observed across the customer's loans (double precision)
            - avgdailyinterestrate: The average daily interest rate observed across the customer's loans (double precision)
            - averagelistrate: The average listed or advertised interest rate for the customer's loans (double precision)
            - totalinterestaccrued: The cumulative total interest accrued across all loans for the customer (double precision)
        """.strip(),
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "loan_terms_interest_rates"
        }
    ),

    Document(
        page_content="""
            Fields related to customerdataproductfinal (Delinquency & Timelines):

            - mindpd: The minimum Days Past Due (DPD) recorded for the customer's loans (bigint)
            - maxdpd: The maximum Days Past Due (DPD) recorded for the customer's loans (bigint)
            - avgdpd: The average Days Past Due (DPD) recorded for the customer's loans (double precision)
            - lastfundedsince: Duration (in days, months, etc.) since the customer's last loan was funded (double precision)
            - lastappsince: Duration (in days, months, etc.) since the customer's last application (double precision)
        """.strip(),
        metadata={
            "table_name": "customerdataproductfinal",
            "chunk_type": "delinquency_timelines"
        }
    ),

]
